name: moon-cathcer publish
on:
  push:
    # We only run this GitHub action upon new commits to `main`
    branches:
      - main
    # We only run this GitHub action if there are changes in the `docs/` directory
    # paths:
    #   - docs/**
    paths-ignore:
      - 'README.md'
      - 'backup/**'
      - '**/*.draft.md'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install and build
        run: npm install && npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_AUTHOR: ${{github.actor}}
          GITHUB_REPOSITORY: ${{github.repository}}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist/client
          # Remove previous build files
          clean: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll